import { Inter } from 'next/font/google';
import './globals.css';
import Header from './components/Header';
import SideBar from './components/SideBar';
import AuthProvider from './Provider/AuthProvider';
import Aos from './components/Aos';
import Navbar from './components/Navbar';
import Footer from './components/Footer';
import SrcollToTopBtn from './components/SrcollToTopBtn';
import TopLoadingLine from './components/TopLoadingLine';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Navbar/>
          {/* <Aos> */}
          {/* <TopLoadingLine/> */}
            {children}
            <SrcollToTopBtn/>
          {/* </Aos> */}
          <Footer/>
        </AuthProvider>
      </body>
    </html>
  );
}